### ISSUE TITLE
Version 4.1.1 breaks expect(...).toEqual(...)

### ISSUE THREAD

**Issue by lacell75** [webdriverio/expect-webdriverio#1029]
With version 4.1.1,  I have an error on expect(1).toEqual(1).

**Behavior:** 
TypeError: this.customTesters is not iterable

**Reproducible example:** 
expect(1).toEqual(1);

```	"devDependencies": {
		"@babel/cli": "7.20.7",
		"@babel/core": "7.20.12",
		"@babel/plugin-proposal-export-default-from": "7.18.10",
		"@babel/preset-env": "7.20.2",
		"@babel/register": "7.18.9",
		"@types/chai": "4.3.4",
		"@types/cheerio": "0.22.31",
		"@types/html-to-text": "9.0.0",
		"@types/jsdom": "20.0.1",
		"@types/node": "18.11.18",
		"@typescript-eslint/eslint-plugin": "5.49.0",
		"@typescript-eslint/parser": "5.49.0",
		"@wdio/appium-service": "8.2.4",
		"@wdio/cli": "8.2.4",
		"@wdio/codemod": "0.12.0",
		"@wdio/dot-reporter": "8.1.2",
		"@wdio/local-runner": "8.2.4",
		"@wdio/mocha-framework": "8.2.3",
		"@wdio/spec-reporter": "8.1.2",
		"allure-commandline": "2.20.1",
		"appium": "1.22.3",
		"babel-jest": "29.4.1",
		"chromedriver": "109.0.0",
		"eslint": "8.33.0",
		"eslint-config-airbnb-base": "15.0.0",
		"eslint-config-prettier": "8.6.0",
		"eslint-import-resolver-typescript": "3.5.3",
		"eslint-plugin-array-func": "3.1.8",
		"eslint-plugin-import": "2.27.5",
		"eslint-plugin-prettier": "4.2.1",
		"eslint-plugin-wdio": "8.0.14",
		"find-unused-exports": "5.0.0",
		"full-icu": "1.5.0",
		"geckodriver": "3.2.0",
		"gherkin-lint": "4.2.2",
		"husky": "8.0.3",
		"jest": "29.4.1",
		"lint-staged": "13.1.0",
		"node-notifier": "10.0.1",
		"npm-run-all": "4.1.5",
		"prettier": "2.8.3",
		"ts-jest": "29.0.5",
		"ts-node": "10.9.1",
		"ts-prune": "0.10.3",
		"typescript": "4.9.4",
		"wdio-chromedriver-service": "8.0.1",
		"wdio-geckodriver-service": "4.0.0",
		"wdio-image-comparison-service": "5.0.2"
	},
	"dependencies": {
		"@types/node-fetch": "2.6.2",
		"@wdio/allure-reporter": "8.2.0",
		"@wdio/cucumber-framework": "8.2.3",
		"@wdio/globals": "8.2.4",
		"axios": "1.1.3",
		"base64-img": "1.0.4",
		"basic-ftp": "5.0.2",
		"chai": "4.3.7",
		"chalk": "5.2.0",
		"cheerio": "1.0.0-rc.12",
		"csv-parse": "5.3.3",
		"date-fns": "2.29.3",
		"depcheck": "1.4.3",
		"docxtemplater": "3.33.0",
		"expect": "29.4.1",
		"expect-webdriverio": "4.1.1",
		"form-data": "4.0.0",
		"fs-extra": "11.1.0",
		"html-to-text": "9.0.3",
		"imap-simple": "5.1.0",
		"jsdom": "21.1.0",
		"jszip": "3.10.1",
		"lodash": "4.17.21",
		"node-fetch": "2.6.8",
		"pizzip": "3.1.4",
		"request": "2.88.2",
		"swagger-typescript-api": "12.0.2",
		"sync-request": "6.1.0",
		"wdio-intercept-service": "4.3.1",
		"webdriverio": "8.2.4",
		"xlsx": "0.18.5",
		"xml-js": "1.6.11",
		"xoauth2": "1.2.0"
	},
```

**Comment by christian-bromann** [comment]
> TypeError: this.customTesters is not iterable

Please provide the whole stack trace.

**Comment by lacell75** [comment]
```
[chrome 109.0.5414.120 WINDOWS #0-0] ------------------------------------------------------------------
[chrome 109.0.5414.120 WINDOWS #0-0] Suite started :
[chrome 109.0.5414.120 WINDOWS #0-0]   » c:\2-gitlab\end-to-end-tests-wdio\features\test.feature
[chrome 109.0.5414.120 WINDOWS #0-0] Content-production.03-Quality Issues.20-Adding/deleting/reading comments INQA-262/263
[0-0] 2023-01-31T13:23:40.361Z DEBUG @wdio/utils:shim: Finished to run "beforeFeature" hook in 1ms

[chrome 109.0.5414.120 WINDOWS #0-0] Teardown if preference don't delete for
[0-0] 2023-01-31T13:23:40.383Z DEBUG @wdio/utils:shim: Finished to run "beforeScenario" hook in 0ms
[chrome 109.0.5414.120 WINDOWS #0-0] Hook executed :
[0-0] 2023-01-31T13:23:40.399Z INFO webdriver: COMMAND getUrl()
[0-0] 2023-01-31T13:23:40.400Z INFO webdriver: [GET] http://localhost:4444/session/d30414378c55485624fe3e2cf4ed90a0/url
[0-0] 2023-01-31T13:23:40.417Z INFO webdriver: RESULT data:,
[0-0] Error in "0: Given I expect"
TypeError: this.customTesters is not iterable
    at World.<anonymous> (file:///C:/2-gitlab/end-to-end-tests-wdio/src/steps/given.js:93:13)
    at async wrapPromiseWithTimeout (C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\time.ts:63:10)
    at async Object.run (C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\user_code_runner.ts:86:16)
    at async Object.run (C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:50:20)
    at async TestCaseRunner.invokeStep (C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:130:12)
    at async TestCaseRunner.runStep (C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:312:20)
    at async C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:214:36
    at async TestCaseRunner.aroundTestStep (C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:162:28)
[0-0] 2023-01-31T13:23:40.418Z DEBUG @wdio/utils:shim: Finished to run "afterStep" hook in 20ms
[chrome 109.0.5414.120 WINDOWS #0-0]    ✖ Given I expect » [ c:\2-gitlab\end-to-end-tests-wdio\features\test.feature ]
[0-0] Save a screenshot
[0-0] 2023-01-31T13:23:40.425Z INFO webdriver: COMMAND takeScreenshot()
```

**Comment by christian-bromann** [comment]
Your error comes from here:

```
TypeError: this.customTesters is not iterable
    at World.<anonymous> (file:///C:/2-gitlab/end-to-end-tests-wdio/src/steps/given.js:93
```

I don't think it is related to `expect-webdriverio`.
