### ISSUE TITLE
Increase in execution time if await is used in the assertion

### ISSUE THREAD

**Issue by lacell75** [webdriverio/expect-webdriverio#1452]
Since #1445 , we see an increase in execution time if an await ii used in assertion. 
For example:
```
describe('Lit component testing', () => {
  it('should increment value on click', async () => {
    render(
      html`<my-element />`,
      document.body
    )
    await expect(await $('myyyy-element')).not.toBeDisplayed();
    const button = await $('my-element').$('>>>button')
    await expect(button).toHaveText('count is 0')

    await button.click()
    await button.click()

    await expect(button).toHaveText('count is 2')
  })
})
```
After analysis, in this specific case, this is a browser instance that is used in toBeDisplayed script, this error is returned instead of false, toBeDisplayed is called during 10s(timeout) :
```
[0-0] [class Browser]
[0-0] TypeError: el.isDisplayed is not, a function
[0-0]     at file:///home/fcellier/monorepo/node_modules/expect-webdriverio/lib/matchers/element/toBeDisplayed.js:11:50
[0-0]     at file:///home/fcellier/monorepo/node_modules/expect-webdriverio/lib/utils.js:52:96
[0-0]     at Object.executeCommand (file:///home/fcellier/monorepo/node_modules/expect-webdriverio/lib/util/executeCommand.js:19:28)
[0-0]     at file:///home/fcellier/monorepo/node_modules/expect-webdriverio/lib/utils.js:52:45
[0-0]     at waitUntil (file:///home/fcellier/monorepo/node_modules/expect-webdriverio/lib/utils.js:23:49)
[0-0]     at Object.executeCommandBe (file:///home/fcellier/monorepo/node_modules/expect-webdriverio/lib/utils.js:51:24)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async Object.toBeDisplayed (file:///home/fcellier/monorepo/node_modules/expect-webdriverio/lib/matchers/element/toBeDisplayed.js:9:20)
[0-0]     at async #handleExpectation (file:///home/fcellier/monorepo/node_modules/@wdio/runner/build/browser.js:297:28)`
```

However, if the await is removed , the execution time is ok. I raise this issue because It's strange that the behavior is different with or without

**Comment by christian-bromann** [comment]
Thanks for filing the issue @lacell75 , can you provide a minimal reproducible example?

**Comment by lacell75** [comment]
> Thanks for filing the issue @lacell75 , can you provide a minimal reproducible example?

Clone this branch https://github.com/lacell75/component-testing-examples/tree/1452
```
cd lit-typescript-vite/
npm run dio
```

**Comment by christian-bromann** [comment]
@lacell75 I can't reproduce the issue. I don't get the error. The only weird thing is that the `toBeDisplayed` takes 10-15s even though the element is not there from the begin with but I don't see the error. Can you verify on your end by updating all dependencies?

**Comment by lacell75** [comment]
I don't see the error too, this error is displayed if added console.log(el.isDisplayed()) into toBeDisplayed script to known why the test takes 10/15s much that without await

**Comment by lacell75** [comment]
thanks @christian-bromann!
