### ISSUE TITLE
`el?.isDisplayed` is not a function

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/expect-webdriverio#1507]
Versions: latest webdriverio + latest expect-webdriverio, TS 5.4.3

Trigger `await expect(await $$('.item')).toBeDisplayed();`

Logs:
```
TypeError: el?.isDisplayed is not a function
    at file:///Users/user/repos/repo/e2e/node_modules/@wdio/runner/node_modules/expect-webdriverio/lib/matchers/element/toBeDisplayed.js:9:74
    at file:///Users/user/repos/repo/e2e/node_modules/@wdio/runner/node_modules/expect-webdriverio/lib/utils.js:55:96
    at Object.executeCommand (file:///Users/user/repos/repo/e2e/node_modules/@wdio/runner/node_modules/expect-webdriverio/lib/util/executeCommand.js:2:26)
    at file:///Users/user/repos/repo/e2e/node_modules/@wdio/runner/node_modules/expect-webdriverio/lib/utils.js:55:45
    at waitUntil (file:///Users/user/repos/repo/e2e/node_modules/@wdio/runner/node_modules/expect-webdriverio/lib/utils.js:26:49)
    at async Object.executeCommandBe (file:///Users/user/repos/repo/e2e/node_modules/@wdio/runner/node_modules/expect-webdriverio/lib/utils.js:54:18)
    at async Object.toBeDisplayed (file:///Users/user/repos/repo/e2e/node_modules/@wdio/runner/node_modules/expect-webdriverio/lib/matchers/element/toBeDisplayed.js:9:20)
    at async Scenario.<anonymous> (file:///Users/user/repos/repo/e2e/steps/my.steps.ts:XX:X)
```

**Comment by christian-bromann** [comment]
@nextlevelbeard do you have a reproducible example for it?

**Comment by sangcnguyen** [comment]
Below is my reproducible code example @christian-bromann 
```
await browser.url("https://webdriver.io/");
await expect(await $$(`//a[@class="navbar__item navbar__link"]`)).toBeDisplayed()
```
It seems the current code accepts `$()`, not `$$()`. I will try to send a PR to extend this capability to accept `$$()`.

**Comment by christian-bromann** [comment]
> Should we add support for handling an array of elements?

What would you think the behavior should be? Should it fail if one of the found elements are not visible?

Generally we only have [one matcher](https://webdriver.io/docs/api/expect-webdriverio#tobeelementsarrayofsize) that allows passing in `WebdriverIO.ElementArrays`. I am not sure what if there is an interest in adding more as you usually only assert one element at a time. However I am open for ideas here.

**Comment by sangcnguyen** [comment]
> What would you think the behavior should be?

I used to write with Selenium, Playwright. I'm hesitant because they don't have behavior like this to check if an array is displayed.
> Should it fail if one of the found elements are not visible?

I think it makes sense to mark the test as a failure if one of the elements is not visible.
> Generally we only have [one matcher](https://webdriver.io/docs/api/expect-webdriverio#tobeelementsarrayofsize) that allows passing in WebdriverIO.ElementArrays. I am not sure what if there is an interest in adding more as you usually only assert one element at a time. However I am open for ideas here.

I think for now we should improve the error messages when the function does not support taking an array element and include the [documentation](https://webdriver.io/docs/api/expect-webdriverio/#tobedisplayed) directly into the [types](https://github.com/webdriverio/expect-webdriverio/blob/fffe99cb53062987a00b2c1fb9115e72d774d7f6/types/expect-webdriverio.d.ts#L160) file. That could help users (including myself) better understand how to use the matchers.

**Comment by christian-bromann** [comment]
> I think for now we should improve the error messages when the function does not support taking an array element

Maybe we can do this for all matchers that expect that? Like having a `validateInput` method that throws if the input is not an `WebdriverIO.Element` or a Promise of that. Also agree with your further suggestions.

**Comment by christian-bromann** [comment]
@htho this is due to the fact that we don't have a better type for these matchers as we currently support matchers for single elements (`$`) and element arrays (`$$`). This could be improved. However most matchers are suppose to only work with single elements.

**Comment by christian-bromann** [comment]
> But [L156](https://github.com/webdriverio/expect-webdriverio/blob/fffe99cb53062987a00b2c1fb9115e72d774d7f6/types/expect-webdriverio.d.ts#L156) claims it is about `$` and `$$`: `// ===== $ or $$ =====`

This doesn't seem correct to me, not sure for what this stands for or if there was a plan to support `expect($$('elem')).toBeExisting()` that would fail if one of the elements would not exist. I doubt that though so it sounds the comment is just wrong.
