### ISSUE TITLE
toHaveTextContaining not working on async mode

### ISSUE THREAD

**Issue by thiagoaslima** [webdriverio/expect-webdriverio#410]
`toHaveText` and `toHaveTextContaining`  do not get the element text correctly

```
it('go to google', async () => {
    await browser.url('http://www.google.com');

    const elem = await $('#SIvCob');

    expect(await elem.getText()).toContain('Google offered in');
    expect(elem).toHaveTextContaining('Google offered in');
  })
```

The assertions should be equivalent, but actually, the second resolves to false.

```
[0-0] {
  passed: true,
  assertion: {
    matcherName: 'toContain',
    passed: true,
    message: '',
    error: undefined,
    errorForStack: undefined,
    actual: 'Google offered in: Français',
    expected: 'Google offered in'
  }
}
[0-0] {
  passed: undefined,
  assertion: {
    matcherName: 'toHaveTextContaining',
    passed: undefined,
    message: "Expected Element({ sessionId: '276a5be58236ede817a24f4e00b3ef3c', elementId: '283acefc-74ce-4fea-9699-ffb41e49b0ba', element-6066-11e4-a52e-4f735466cecf: '283acefc-74ce-4fea-9699-ffb41e49b0ba', selector: '#SIvCob', parent: Browser({ sessionId: '276a5be58236ede817a24f4e00b3ef3c', capabilities: Object({ acceptInsecureCerts: true, browserName: 'chrome', browserVersion: '90.0.4430.85', chrome: Object({ chromedriverVersion: '90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})', userDataDir: '/var/folders/x8/c58l8cz10x7gkpf7wy1hxcv00000gn/T/.com.google.Chrome.CscXpN' }), goog:chromeOptions: Object({ debuggerAddress: 'localhost:52180' }), networkConnectionEnabled: false, pageLoadStrategy: 'normal', platformName: 'mac os x', proxy: Object({  }), setWindowRect: true, strictFileInteractability: false, timeouts: Object({ implicit: 0, pageLoad: 300000, script: 30000 }), unhandledPromptBehavior: 'dismiss and notify', webauthn:extension:largeBlob: true, webauthn:virtualA ... to have text containing 'Google offered in'.",
    error: undefined,
    errorForStack: undefined,
    actual: Element {
      sessionId: '276a5be58236ede817a24f4e00b3ef3c',
      elementId: '283acefc-74ce-4fea-9699-ffb41e49b0ba',
      'element-6066-11e4-a52e-4f735466cecf': '283acefc-74ce-4fea-9699-ffb41e49b0ba',
      selector: '#SIvCob',
      parent: [Browser],
      emit: [Function: bound ],
      isReactElement: false,
      addCommand: [Function (anonymous)],
      overwriteCommand: [Function (anonymous)]
    },
    expected: 'Google offered in'
  }
}
[0-0] {
  passed: false,
  assertion: {
    matcherName: '',
    passed: false,
    expected: '',
    actual: '',
    error: {
      matcherName: 'toHaveTextContaining',
      message: "Expected Element({ sessionId: '276a5be58236ede817a24f4e00b3ef3c', elementId: '283acefc-74ce-4fea-9699-ffb41e49b0ba', element-6066-11e4-a52e-4f735466cecf: '283acefc-74ce-4fea-9699-ffb41e49b0ba', selector: '#SIvCob', parent: Browser({ sessionId: '276a5be58236ede817a24f4e00b3ef3c', capabilities: Object({ acceptInsecureCerts: true, browserName: 'chrome', browserVersion: '90.0.4430.85', chrome: Object({ chromedriverVersion: '90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})', userDataDir: '/var/folders/x8/c58l8cz10x7gkpf7wy1hxcv00000gn/T/.com.google.Chrome.CscXpN' }), goog:chromeOptions: Object({ debuggerAddress: 'localhost:52180' }), networkConnectionEnabled: false, pageLoadStrategy: 'normal', platformName: 'mac os x', proxy: Object({  }), setWindowRect: true, strictFileInteractability: false, timeouts: Object({ implicit: 0, pageLoad: 300000, script: 30000 }), unhandledPromptBehavior: 'dismiss and notify', webauthn:extension:largeBlob: true, webauthn:virtualA ... to have text containing 'Google offered in'.",
      stack: "Error: Expected Element({ sessionId: '276a5be58236ede817a24f4e00b3ef3c', elementId: '283acefc-74ce-4fea-9699-ffb41e49b0ba', element-6066-11e4-a52e-4f735466cecf: '283acefc-74ce-4fea-9699-ffb41e49b0ba', selector: '#SIvCob', parent: Browser({ sessionId: '276a5be58236ede817a24f4e00b3ef3c', capabilities: Object({ acceptInsecureCerts: true, browserName: 'chrome', browserVersion: '90.0.4430.85', chrome: Object({ chromedriverVersion: '90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})', userDataDir: '/var/folders/x8/c58l8cz10x7gkpf7wy1hxcv00000gn/T/.com.google.Chrome.CscXpN' }), goog:chromeOptions: Object({ debuggerAddress: 'localhost:52180' }), networkConnectionEnabled: false, pageLoadStrategy: 'normal', platformName: 'mac os x', proxy: Object({  }), setWindowRect: true, strictFileInteractability: false, timeouts: Object({ implicit: 0, pageLoad: 300000, script: 30000 }), unhandledPromptBehavior: 'dismiss and notify', webauthn:extension:largeBlob: true, webauthn:virtualA ... to have text containing 'Google offered in'.\n" +
        '    at <Jasmine>\n' +
        '    at Spec.addExpectationResult (/Users/thiagolima/Documents/neo/member-portal/node_modules/@wdio/jasmine-framework/build/index.js:296:32)\n' +
        '    at <Jasmine>\n' +
        '    at UserContext.<anonymous> (/Users/thiagolima/Documents/neo/member-portal/test/wdio/tests/login.test.ts:32:18)\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
      passed: undefined,
      expected: 'Google offered in',
      actual: [Element]
    }
  }
}
```

**Comment by christian-bromann** [comment]
@thiagoaslima if you use async mode you need to put `await` in front of the `expect`, e.g.:
```js
it('go to google', async () => {
    await browser.url('http://www.google.com');

    const elem = await $('#SIvCob');

    expect(await elem.getText()).toContain('Google offered in');
    await expect(elem).toHaveTextContaining('Google offered in');
})
```
Let me know if you have further questions.

**Comment by thiagoaslima** [comment]
@christian-bromann Sorry. As it wasn't working, I've tried without the await and sent you the wrong version.
Anyways, I see the same behavior. The test fails with the expected value read as undefined.

```
it('go to google', async () => {
    await browser.url('http://www.google.com');
    const elem = await $('#SIvCob');
    await expect(elem).toHaveTextContaining('Google offered in');
  })
  ```

As you can see, the driver asserts it 3 times, always with `passed: undefined`

```
[0-0] [90m2021-04-25T06:46:57.135Z[39m [32mDEBUG[39m [97m@wdio/local-runner:utils[39m: init remote session
[90m2021-04-25T06:46:57.135Z[39m [96mINFO[39m [97mwebdriver[39m: Initiate new session using the WebDriver protocol
[0-0] [90m2021-04-25T06:46:57.136Z[39m [96mINFO[39m [97mwebdriver[39m: [POST] http://localhost:9515/session
[0-0] [90m2021-04-25T06:46:57.136Z[39m [96mINFO[39m [97mwebdriver[39m: [33mDATA[39m {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-0] [90m2021-04-25T06:46:57.879Z[39m [32mDEBUG[39m [97m@wdio/utils:shim[39m: Finished to run "before" hook in 0ms
[0-0] [90m2021-04-25T06:46:57.888Z[39m [96mINFO[39m [97mwebdriver[39m: [35mCOMMAND[39m navigateTo("http://www.google.com/")
[90m2021-04-25T06:46:57.888Z[39m [96mINFO[39m [97mwebdriver[39m: [POST] http://localhost:9515/session/844d4d410b8f16dc182c5ef40909ed8e/url
[90m2021-04-25T06:46:57.888Z[39m [96mINFO[39m [97mwebdriver[39m: [33mDATA[39m { url: 'http://www.google.com/' }
[0-0] [90m2021-04-25T06:46:58.907Z[39m [96mINFO[39m [97mwebdriver[39m: [35mCOMMAND[39m findElement("css selector", "#SIvCob")
[0-0] [90m2021-04-25T06:46:58.908Z[39m [96mINFO[39m [97mwebdriver[39m: [POST] http://localhost:9515/session/844d4d410b8f16dc182c5ef40909ed8e/element
[0-0] [90m2021-04-25T06:46:58.908Z[39m [96mINFO[39m [97mwebdriver[39m: [33mDATA[39m { using: 'css selector', value: '#SIvCob' }
[0-0] [90m2021-04-25T06:46:58.915Z[39m [96mINFO[39m [97mwebdriver[39m: [36mRESULT[39m {
  'element-6066-11e4-a52e-4f735466cecf': '25f5cd90-36ea-4f0b-b2fb-7334df46cbde'
}
[0-0] {
  passed: undefined,
  assertion: {
    matcherName: 'toHaveTextContaining',
    passed: undefined,
    message: "Expected Element({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', elementId: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', element-6066-11e4-a52e-4f735466cecf: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', selector: '#SIvCob', parent: Browser({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', capabilities: Object({ acceptInsecureCerts: true, browserName: 'chrome', browserVersion: '90.0.4430.85', chrome: Object({ chromedriverVersion: '90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})', userDataDir: '/var/folders/x8/c58l8cz10x7gkpf7wy1hxcv00000gn/T/.com.google.Chrome.DWERw1' }), goog:chromeOptions: Object({ debuggerAddress: 'localhost:59074' }), networkConnectionEnabled: false, pageLoadStrategy: 'normal', platformName: 'mac os x', proxy: Object({  }), setWindowRect: true, strictFileInteractability: false, timeouts: Object({ implicit: 0, pageLoad: 300000, script: 30000 }), unhandledPromptBehavior: 'dismiss and notify', webauthn:extension:largeBlob: true, webauthn:virtualA ... to have text containing 'Google offered in'.",
    error: undefined,
    errorForStack: undefined,
    actual: Element {
      sessionId: '844d4d410b8f16dc182c5ef40909ed8e',
      elementId: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde',
      'element-6066-11e4-a52e-4f735466cecf': '25f5cd90-36ea-4f0b-b2fb-7334df46cbde',
      selector: '#SIvCob',
      parent: [Browser],
      emit: [Function: bound ],
      isReactElement: false,
      addCommand: [Function (anonymous)],
      overwriteCommand: [Function (anonymous)]
    },
    expected: 'Google offered in'
  }
}
[0-0] {
  passed: false,
  assertion: {
    matcherName: '',
    passed: false,
    expected: '',
    actual: '',
    error: {
      matcherName: 'toHaveTextContaining',
      message: "Expected Element({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', elementId: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', element-6066-11e4-a52e-4f735466cecf: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', selector: '#SIvCob', parent: Browser({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', capabilities: Object({ acceptInsecureCerts: true, browserName: 'chrome', browserVersion: '90.0.4430.85', chrome: Object({ chromedriverVersion: '90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})', userDataDir: '/var/folders/x8/c58l8cz10x7gkpf7wy1hxcv00000gn/T/.com.google.Chrome.DWERw1' }), goog:chromeOptions: Object({ debuggerAddress: 'localhost:59074' }), networkConnectionEnabled: false, pageLoadStrategy: 'normal', platformName: 'mac os x', proxy: Object({  }), setWindowRect: true, strictFileInteractability: false, timeouts: Object({ implicit: 0, pageLoad: 300000, script: 30000 }), unhandledPromptBehavior: 'dismiss and notify', webauthn:extension:largeBlob: true, webauthn:virtualA ... to have text containing 'Google offered in'.",
      stack: "Error: Expected Element({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', elementId: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', element-6066-11e4-a52e-4f735466cecf: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', selector: '#SIvCob', parent: Browser({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', capabilities: Object({ acceptInsecureCerts: true, browserName: 'chrome', browserVersion: '90.0.4430.85', chrome: Object({ chromedriverVersion: '90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})', userDataDir: '/var/folders/x8/c58l8cz10x7gkpf7wy1hxcv00000gn/T/.com.google.Chrome.DWERw1' }), goog:chromeOptions: Object({ debuggerAddress: 'localhost:59074' }), networkConnectionEnabled: false, pageLoadStrategy: 'normal', platformName: 'mac os x', proxy: Object({  }), setWindowRect: true, strictFileInteractability: false, timeouts: Object({ implicit: 0, pageLoad: 300000, script: 30000 }), unhandledPromptBehavior: 'dismiss and notify', webauthn:extension:largeBlob: true, webauthn:virtualA ... to have text containing 'Google offered in'.\n" +
        '    at <Jasmine>\n' +
        '    at Spec.addExpectationResult (/Users/thiagolima/Documents/neo/member-portal/node_modules/@wdio/jasmine-framework/build/index.js:296:32)\n' +
        '    at <Jasmine>\n' +
        '    at UserContext.<anonymous> (/Users/thiagolima/Documents/neo/member-portal/test/wdio/tests/login.test.ts:36:24)\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
      passed: undefined,
      expected: 'Google offered in',
      actual: [Element]
    }
  }
}
[0-0] {
  passed: false,
  assertion: {
    matcherName: '',
    passed: false,
    expected: '',
    actual: '',
    error: {
      matcherName: 'toHaveTextContaining',
      message: "Expected Element({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', elementId: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', element-6066-11e4-a52e-4f735466cecf: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', selector: '#SIvCob', parent: Browser({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', capabilities: Object({ acceptInsecureCerts: true, browserName: 'chrome', browserVersion: '90.0.4430.85', chrome: Object({ chromedriverVersion: '90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})', userDataDir: '/var/folders/x8/c58l8cz10x7gkpf7wy1hxcv00000gn/T/.com.google.Chrome.DWERw1' }), goog:chromeOptions: Object({ debuggerAddress: 'localhost:59074' }), networkConnectionEnabled: false, pageLoadStrategy: 'normal', platformName: 'mac os x', proxy: Object({  }), setWindowRect: true, strictFileInteractability: false, timeouts: Object({ implicit: 0, pageLoad: 300000, script: 30000 }), unhandledPromptBehavior: 'dismiss and notify', webauthn:extension:largeBlob: true, webauthn:virtualA ... to have text containing 'Google offered in'.",
      stack: "Error: Expected Element({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', elementId: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', element-6066-11e4-a52e-4f735466cecf: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', selector: '#SIvCob', parent: Browser({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', capabilities: Object({ acceptInsecureCerts: true, browserName: 'chrome', browserVersion: '90.0.4430.85', chrome: Object({ chromedriverVersion: '90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})', userDataDir: '/var/folders/x8/c58l8cz10x7gkpf7wy1hxcv00000gn/T/.com.google.Chrome.DWERw1' }), goog:chromeOptions: Object({ debuggerAddress: 'localhost:59074' }), networkConnectionEnabled: false, pageLoadStrategy: 'normal', platformName: 'mac os x', proxy: Object({  }), setWindowRect: true, strictFileInteractability: false, timeouts: Object({ implicit: 0, pageLoad: 300000, script: 30000 }), unhandledPromptBehavior: 'dismiss and notify', webauthn:extension:largeBlob: true, webauthn:virtualA ... to have text containing 'Google offered in'.\n" +
        '    at <Jasmine>\n' +
        '    at Spec.addExpectationResult (/Users/thiagolima/Documents/neo/member-portal/node_modules/@wdio/jasmine-framework/build/index.js:296:32)\n' +
        '    at <Jasmine>\n' +
        '    at UserContext.<anonymous> (/Users/thiagolima/Documents/neo/member-portal/test/wdio/tests/login.test.ts:36:24)\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
      passed: undefined,
      expected: 'Google offered in',
      actual: [Element]
    }
  }
}
[0-0] [90m2021-04-25T06:46:58.930Z[39m [96mINFO[39m [97mwebdriver[39m: [35mCOMMAND[39m getElementText("25f5cd90-36ea-4f0b-b2fb-7334df46cbde")
[0-0] [90m2021-04-25T06:46:58.931Z[39m [96mINFO[39m [97mwebdriver[39m: [GET] http://localhost:9515/session/844d4d410b8f16dc182c5ef40909ed8e/element/25f5cd90-36ea-4f0b-b2fb-7334df46cbde/text
[0-0] Error in "webdriver.io go to google"
Error: Expected Element({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', elementId: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', element-6066-11e4-a52e-4f735466cecf: '25f5cd90-36ea-4f0b-b2fb-7334df46cbde', selector: '#SIvCob', parent: Browser({ sessionId: '844d4d410b8f16dc182c5ef40909ed8e', capabilities: Object({ acceptInsecureCerts: true, browserName: 'chrome', browserVersion: '90.0.4430.85', chrome: Object({ chromedriverVersion: '90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})', userDataDir: '/var/folders/x8/c58l8cz10x7gkpf7wy1hxcv00000gn/T/.com.google.Chrome.DWERw1' }), goog:chromeOptions: Object({ debuggerAddress: 'localhost:59074' }), networkConnectionEnabled: false, pageLoadStrategy: 'normal', platformName: 'mac os x', proxy: Object({  }), setWindowRect: true, strictFileInteractability: false, timeouts: Object({ implicit: 0, pageLoad: 300000, script: 30000 }), unhandledPromptBehavior: 'dismiss and notify', webauthn:extension:largeBlob: true, webauthn:virtualA ... to have text containing 'Google offered in'.
    at <Jasmine>
    at <Jasmine>
    at UserContext.<anonymous> (/Users/thiagolima/Documents/neo/member-portal/test/wdio/tests/login.test.ts:36:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[0-0] [90m2021-04-25T06:46:58.937Z[39m [96mINFO[39m [97mwebdriver[39m: [35mCOMMAND[39m deleteSession()
[0-0] [90m2021-04-25T06:46:58.937Z[39m [96mINFO[39m [97mwebdriver[39m: [DELETE] http://localhost:9515/session/844d4d410b8f16dc182c5ef40909ed8e
[0-0] [90m2021-04-25T06:46:58.940Z[39m [96mINFO[39m [97mwebdriver[39m: [36mRESULT[39m Google offered in: Français
2021-04-25T06:46:59.111Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - /test/wdio/tests/login.test.ts
2021-04-25T06:46:59.112Z INFO @wdio/cli:launcher: Run onComplete hook
2021-04-25T06:46:59.112Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms
```

**Comment by sbley** [comment]
Should this be reopened then?
I noticed the same behavior as the issue creator.

**Comment by christian-bromann** [comment]
@sbley if you are using `jasmine` make sure to use [`expectAsync`](https://jasmine.github.io/api/3.7/async-matchers.html)

**Comment by sbley** [comment]
That did the trick, thank you!
