### ISSUE TITLE
toHaveChildren broken

### ISSUE THREAD

**Issue by muhserks** [webdriverio/expect-webdriverio#586]
Hi,

I recently updated from WDIO@7.9.0 to WDIO@7.16.3 and now toHaveChildren does not work at all anymore. 

`expect(this.myList).not.toHaveChildren();`
Results in:
```
TypeError: Cannot read property 'message' of undefined
    at Object.enhanceError (C:\GITXXX\YYY\node_modules\expect-webdriverio\lib\util\formatMessage.js:41:91)
    at C:\GITXXX\YYY\node_modules\expect-webdriverio\lib\matchers\element\toHaveChildren.js:41:33
    at async Browser.runCommandWithHooks (C:\GITXXX\YYY\node_modules\@wdio\sync\build\wrapCommand.js:105:25)
    at Browser.runCommandWithHooks (C:\GITXXX\YYY\node_modules\@wdio\sync\build\wrapCommand.js:100:24)
    at Browser.wrapCommandFn (C:\GITXXX\YYY\node_modules\@wdio\sync\build\wrapCommand.js:67:44) 
    at Browser.<anonymous> (C:\GITXXX\YYY\node_modules\@wdio\utils\build\shim.js:270:24)        
    at Object.toHaveChildrenFn (C:\GITXXX\YYY\node_modules\expect-webdriverio\lib\matchers\element\toHaveChildren.js:29:20)
    at Object.runJestExpect (C:\GITXXX\YYY\node_modules\expect-webdriverio\lib\util\expectAdapter.js:10:15)
    at Object.toHaveChildren (C:\GITXXX\YYY\node_modules\expect-webdriverio\lib\matchers\element\toHaveChildren.js:49:38)
    at __EXTERNAL_MATCHER_TRAP__ (C:\GITXXX\YYY\node_modules\expect\build\index.js:386:30)      
    at Object.throwingMatcher [as toHaveChildren] (C:\GITXXX\YYY\node_modules\expect\build\index.js:387:15)
    at MessageBox.assertNoRecipientsTo (C:\GITXXX\YYY\src\pageobjects\satellites\MessageBox.ts:130:43)
    at Context.<anonymous> (C:\GITXXX\YYY\src\specs\ZZZ\GGG\DDDD\DATEST.ts:43:26)
```

`expect(this.recipientToList).toHaveChildren(0);`
results in:
```
Error: Expect $(`#myListElement`) to have children

Expected: "no params"
Received: 0

```

`expect(this.myList).not.toHaveChildren(0);`
This does not even throw an error, even tough the element has no childrens.

According to the wdio docs, all calls should work. In fact, before updating wdio it worked.

Any idea?

**Comment by muhserks** [comment]
@christian-bromann 

The issue started with expect-webdriverio@3.1.2.
Looking into the unit test (https://github.com/webdriverio/expect-webdriverio/blob/main/test/matchers/element/toHaveChildren.test.ts) shows also that no test exists where no parameter is passed, even though it is described in the docs that it should be possible (https://webdriver.io/docs/api/expect-webdriverio/#tohavechildren):
``await expect(list).toHaveChildren() // the list has at least one item``

When passing an object it works, as already stated above. 

Does **not** Work:
``expect($('//div/p')).not.toHaveChildren();``
``expect($('//div/p')).toHaveChildren(0);``

Does Work:
``expect($('//div/p')).not.toHaveChildren({});``

**Comment by shoobyban** [comment]
Please fix this. You just have to modify 
https://github.com/webdriverio/expect-webdriverio/blob/e598db5137f7732b33c9d2e59bb54d98e8df9968/src/matchers/element/toHaveChildren.ts#L8
so it's 
```javascript
    if (!options.lte && !options.gte && (typeof options.eq !== 'number')) {
```

**Comment by christian-bromann** [comment]
@shoobyban feel free to provide a PR with a fix, thanks!
